resolver: lts-16.21
extra-deps:
# diagrams and SVG
  - diagrams-core-1.4.2
  - diagrams-lib-1.4.3
  - diagrams-svg-1.4.3
  - svg-builder-0.1.1
# Csound
  - wl-pprint-1.2.1
  - csound-expression-dynamic-0.3.3
  - csound-expression-opcodes-0.0.4.0
  - csound-expression-typed-0.2.2.0
  - temporal-media-0.6.3
  - data-fix-0.2.0
  - data-fix-cse-0.0.2
  - csound-expression-5.3.2
  - csound-catalog-0.7.3
  - csound-sampler-0.0.9.0
  - sharc-timbre-0.2
# port midi
  - PortMidi-0.2.0.0
# Threepenny-GUI for nice JavaScript experiments
#  - file-embed-0.0.10.1
#  - threepenny-gui-0.8.2.0
#  - exceptions-0.10.0
#  - hint-0.8.0
# Henning's stuff
  - blas-ffi-0.1
  - comfort-array-0.3.1
  - guarded-allocation-0.0.1
  - lapack-ffi-0.0.2
  - netlib-ffi-0.1.1
  - primitive-0.7.1.0
  - boxes-0.1.5
  - tfp-1.0.1.1
packages:
  - hyper
  - hyper-extra
  - hyper-haskell-server

