resolver: lts-9.10
extra-deps:
#  we need a custom version of hint
#  - hint-0.6.0
# diagrams and SVG
  - diagrams-core-1.4.0.1
  - diagrams-lib-1.4.1.2
  - diagrams-svg-1.4.1.1
  - svg-builder-0.1.0.2
# Csound
  - wl-pprint-1.2.1
  - csound-expression-dynamic-0.3.3
  - csound-expression-opcodes-0.0.4.0
  - csound-expression-typed-0.2.2.0
  - temporal-media-0.6.3
  - data-fix-0.2.0
  - data-fix-cse-0.0.2
  - csound-expression-5.3.2
  - csound-catalog-0.7.3
  - csound-sampler-0.0.9.0
  - sharc-timbre-0.2
# port midi
  - PortMidi-0.2.0.0
# Threepenny-GUI for nice JavaScript experiments
  - file-embed-0.0.10.1
  - threepenny-gui-0.8.2.0
  - exceptions-0.10.0
  - hint-0.8.0
packages:
  - hyper
  - hyper-extra
  - hyper-haskell-server
#  - location:
#      git: https://github.com/mvdan/hint
#      commit: f10e357d8249bc4b8a71e2c211bebc202549c765
#    extra-dep: true
#  - location: lib/hint-0.4.2.3-patched
#    extra-dep: true
